#!/bin/sh
set -euf

##
# SSH script to print local host server public key fingerprints.
#
# Typical locations for fingerprints:
#
#   * Debian: /etc/ssh/ssh_host*.pub
#   * OSX: /etc/ssh_host*.pub
#
# Compare `ssh-fingerprints-of-remote-host`.
#
# Command: ssh-fingerprints-of-locale-host
# Version: 1.3.0
# License: GPL
# Created: 2015-01-25
# Updated: 2016-08-19
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

find -L /etc ! -perm +222 -prune -o -name 'ssh_host*.pub' -print |
xargs -I{} ssh-keygen -l -f {}